export enum ActionType {
  // Events
  EVENTS_GET = 'EVENTS/GET_ALL',
  EVENTS_DELETE = 'EVENTS/DELETE',
  EVENTS_UPDATE = 'EVENTS/UPDATE',
  EVENTS_CREATE = 'EVENTS/CREATE',
  EVENTS_GET_BY_ID = 'EVENTS/GET_BY_ID',
  // Events DB
  EVENTS_DB_GET = 'EVENTS/DB_GET_ALL',
  EVENTS_DB_DELETE = 'EVENTS/DB_DELETE',
  EVENTS_DB_UPDATE = 'EVENTS/DB_UPDATE',
  EVENTS_DB_CREATE = 'EVENTS/DB_CREATE',
  EVENTS_DB_GET_BY_ID = 'EVENTS/DB_GET_BY_ID',
  //Current date
  CURRENT_DATE_UPDATE = 'CURRENT_DATE/UPDATE',
  //Create user DB
  USER_DB_CREATE = 'USER/DB_CREATE',
}
