export enum ActionType {
  // Events
  EVENTS_GET = 'EVENTS/GET_ALL',
  EVENTS_DELETE = 'EVENTS/DELETE',
  EVENTS_UPDATE = 'EVENTS/UPDATE',
  EVENTS_CREATE = 'EVENTS/CREATE',
  EVENTS_GET_BY_ID = 'EVENTS/GET_BY_ID',
  CURRENT_DATE_UPDATE = 'CURRENT_DATE/UPDATE',
}
